### ISSUE TITLE
Imported blocklists don’t block sometimes

### ISSUE THREAD

**Issue by Yquas** [Gedsh/InviZible#86]
This issue didn’t happen since the first time I used InviZible, but since some of the 1.2.x betas (I think 1.2.2 to 1.2.4, but sadly I do not know which one exactly). And it seems to more often since 1.2.5, I think.
The problem is that sometimes, always directly after startup, never after having run for a longer time already, the DNS log shows all "Googley" and "Xiaomiey" connections like finddeviceapi, mtalk, googleapis, gstatic, data-mistat-xiaomi and more in green and also in the longer resolved versions, which to me clearly means they’re let through and used. But I blocked all those things in my imported blacklists. And even if I import those blacklists again and again during the time where all is let through, it is still left unblocked. I have to turn off the entire InviZible and turn it back (with the big start/stop button) on to make it work, sometimes it even happens again after that. And force-stopping InviZible also seems to help sometimes. But it always returns at some new startup of InviZible. That’s really annoying.
The firewall would solve this temporarily, but as I said in my issue #85, I cannot use the firewall or it makes half of my phone unusable.
Can this be fixed? What is the problem?

**Comment by Yquas** [comment]
Luckily my firewall issue could easily be fixed, so this issue can be solved in a different way. But I think this is still a weird bug.

**Comment by Gedsh** [comment]
> The problem is that sometimes, always directly after startup, never after having run for a longer time already, the DNS log shows all "Googley" and "Xiaomiey" connections like finddeviceapi, mtalk, googleapis, gstatic, data-mistat-xiaomi and more in green and also in the longer resolved versions, which to me clearly means they’re let through and used. But I blocked all those things in my imported blacklists.

After phone startup it takes a while for InviZible to start. During this time apps can resolve blocked in DNSCrypt blacklist sites, save returned IP addresses in cache and later use them and in such a way bypass blocking.

Enabling Always On VPN and Blocking connections without VPN should fix the problem. But some phones, like Xiaomi, may not consider this option or bypass VPN service altogether for some system apps.

To avoid startup problems, it is best to turn off the internet before restarting your phone and turn it on only after InviZible has started.

**Comment by Yquas** [comment]
@Gedsh I was not clear, I was just talking about the starting of InviZible, not the phone. I turn off internet and InviZible when I don't use the phone for a longer time of the day. Amd when I go to use it again (and turn both on), this sometimes happens.
I have enabled always on VPN and block connections without VPN since I first use InviZible, so that's also no problem.
And I pretty much always turn off the internet before shutting down the phone. But I turn on internet _before_ starting InviZible. Should that be the other way around or did I misunderstand you?

**Comment by Gedsh** [comment]
> But I turn on internet before starting InviZible.

You should start InviZible before turning on the Internet. Or is it better not to stop it at all.

**Comment by Yquas** [comment]
@Gedsh I am stopping it to not make it consume power when being offline. And I tries starting it before turning it on, but that doesn't fix anything. Without the firewall, the connections would just go through. I'd have to reload the blocklists to stop it, and it also doesn't always work.

**Comment by Gedsh** [comment]
Make sure Private DNS is OFF in your phone settings.

Are the hosts actually reachable or is it logs show wrong?

**Comment by Yquas** [comment]
@Gedsh Private DNS was always off, that's no problem. And about the reachability: I don't know. Those are mostly tracking sites so they aren't meant to be visited by a browser anyway, so they'd tell me some weird errors. But I'll look at it.

_Sent from my Mi MIX 2S using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_
